[package]
name = 'escrow'
version = '1.0.0'

[addresses]
escrow = "_"

[dependencies]
AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'devnet', subdir = 'aptos-move/framework/aptos-framework'}